In [1]:
import torch
import torch.nn as nn
import torch.nn.functional as F
import torch.optim as optim

torch.manual_seed(1)

In [4]:
x_data= [[1,2],   # (6,2)
         [2,3],
         [3,1],
         [4,3],
         [5,3],
         [6,2]]


y_data = [[0],[0],[0],[1],[1],[1]]    # (6,1)

In [5]:
x_train = torch.FloatTensor(x_data)
y_train = torch.FloatTensor(y_data)

In [6]:
print(x_train.shape)
print(y_train.shape)

torch.Size([6, 2])
torch.Size([6, 1])


In [7]:
W = torch.zeros((2,1), requires_grad = True)
b = torch.zeros(1, requires_grad = True)

hypothesis = 1 / (1+torch.exp(-(x_train.matmul(W)+b )))

In [9]:
print(hypothesis)
print(hypothesis.shape)

tensor([[0.5000],
        [0.5000],
        [0.5000],
        [0.5000],
        [0.5000],
        [0.5000]], grad_fn=<MulBackward0>)
torch.Size([6, 1])


In [10]:
hypothesis = torch.sigmoid(x_train.matmul(W) + b)

print(hypothesis)
print(hypothesis.shape)

tensor([[0.5000],
        [0.5000],
        [0.5000],
        [0.5000],
        [0.5000],
        [0.5000]], grad_fn=<SigmoidBackward>)
torch.Size([6, 1])


In [16]:
losses = -(y_train * torch.log(hypothesis) + (1-y_train)*torch.log(1-hypothesis))
print(losses)

tensor([[0.6931],
        [0.6931],
        [0.6931],
        [0.6931],
        [0.6931],
        [0.6931]], grad_fn=<NegBackward>)


In [17]:
cost = losses.mean()
print(cost)

tensor(0.6931, grad_fn=<MeanBackward0>)


In [18]:
F.binary_cross_entropy(hypothesis,y_train)

tensor(0.6931, grad_fn=<BinaryCrossEntropyBackward>)

In [22]:
optimizer = optim.SGD([W,b] , lr = 1)

nb_epochs = 1000
for epoch in range(nb_epochs + 1):
    hypothesis = torch.sigmoid(x_train.matmul(W) + b)
    cost = F.binary_cross_entropy(hypothesis, y_train)
    
    optimizer.zero_grad()
    cost.backward()
    
    optimizer.step()
    
    if epoch % 100 == 0:
        print("Epoch {:4d}/{} Cost: {:.6f}".format(epoch,nb_epochs,cost.item()))
    

Epoch    0/1000 Cost: 0.010295
Epoch  100/1000 Cost: 0.009824
Epoch  200/1000 Cost: 0.009394
Epoch  300/1000 Cost: 0.009001
Epoch  400/1000 Cost: 0.008639
Epoch  500/1000 Cost: 0.008305
Epoch  600/1000 Cost: 0.007996
Epoch  700/1000 Cost: 0.007709
Epoch  800/1000 Cost: 0.007442
Epoch  900/1000 Cost: 0.007193
Epoch 1000/1000 Cost: 0.006960
