In [1]:
import tensorflow as tf
import numpy as np

print(tf.__version__)

2.0.0


In [2]:
tf.random.set_seed(0)

# Simple Example 2 variables

In [7]:
x1_data = [1,0,3,0,5]
x2_data = [0,2,0,4,0]
y_data = [1,2,3,4,5]

W1 = tf.Variable(tf.random.uniform((1,), -10.0, 10.0))
W2 = tf.Variable(tf.random.uniform((1,), -10.0, 10.0))
b = tf.Variable(tf.random.uniform((1,), -10.0, 10.0))

learning_rate = tf.Variable(0.001)

for i in range(1000+1):
    with tf.GradientTape() as tape:
        hypothesis = W1 * x1_data + W2 * x2_data + b
        cost = tf.reduce_mean(tf.square(hypothesis - y_data))
    W1_grad,W2_grad,b_grad = tape.gradient(cost, [W1,W2,b])
    W1.assign_sub(learning_rate*W1_grad)
    W2.assign_sub(learning_rate*W2_grad)
    b.assign_sub(learning_rate*b_grad)
    
    if i % 50 == 0:
        print("{:5} | {:10.6f} | {:10.4f} | {:10.4f} | {:10.6f}".format(
          i, cost.numpy(), W1.numpy()[0], W2.numpy()[0], b.numpy()[0]))
        

    0 | 298.163208 |    -2.0312 |    -8.8716 |   5.555960
   50 | 123.566689 |    -1.2893 |    -6.2081 |   6.438887
  100 |  56.342140 |    -1.0056 |    -4.4898 |   6.908751
  150 |  29.300915 |    -0.9084 |    -3.3732 |   7.144037
  200 |  18.064541 |    -0.8805 |    -2.6416 |   7.243129
  250 |  13.235641 |    -0.8734 |    -2.1573 |   7.261687
  300 |  11.051542 |    -0.8686 |    -1.8323 |   7.231983
  350 |   9.972128 |    -0.8601 |    -1.6102 |   7.173151
  400 |   9.359201 |    -0.8469 |    -1.4548 |   7.096750
  450 |   8.946493 |    -0.8297 |    -1.3426 |   7.009877
  500 |   8.622438 |    -0.8094 |    -1.2586 |   6.916938
  550 |   8.340123 |    -0.7870 |    -1.1929 |   6.820694
  600 |   8.079732 |    -0.7633 |    -1.1393 |   6.722889
  650 |   7.832807 |    -0.7388 |    -1.0937 |   6.624624
  700 |   7.595675 |    -0.7139 |    -1.0534 |   6.526597
  750 |   7.366667 |    -0.6889 |    -1.0168 |   6.429249
  800 |   7.144961 |    -0.6640 |    -0.9827 |   6.332852
  850 |   6.93

# Simple Example 2 variables with Matrix

In [13]:
x_data = [
    [1., 0., 3., 0., 5.],
    [0., 2., 0., 4., 0.]
]
y_data  = [1, 2, 3, 4, 5]

W = tf.Variable(tf.random.uniform((1, 2), -1.0, 1.0))
b = tf.Variable(tf.random.uniform((1,), -1.0, 1.0))

learning_rate = tf.Variable(0.001)

for i in range(1000+1):
    with tf.GradientTape() as tape:
        hypothesis = tf.matmul(W, x_data) + b # (1, 2) * (2, 5) = (1, 5)
        cost = tf.reduce_mean(tf.square(hypothesis - y_data))

        W_grad, b_grad = tape.gradient(cost, [W, b])
        W.assign_sub(learning_rate * W_grad)
        b.assign_sub(learning_rate * b_grad)
    
    if i % 50 == 0:
        print("{:5} | {:10.6f} | {:10.4f} | {:10.4f} | {:10.6f}".format(
            i, cost.numpy(), W.numpy()[0][0], W.numpy()[0][1], b.numpy()[0]))

    0 |  16.191433 |    -0.1438 |     0.0907 |  -0.483252
   50 |   4.108324 |     0.4768 |     0.4242 |  -0.217644
  100 |   1.135702 |     0.7591 |     0.6284 |  -0.081244
  150 |   0.348200 |     0.8860 |     0.7553 |  -0.009809
  200 |   0.118523 |     0.9420 |     0.8350 |   0.028319
  250 |   0.044205 |     0.9660 |     0.8856 |   0.048983
  300 |   0.017833 |     0.9760 |     0.9179 |   0.060262
  350 |   0.007802 |     0.9798 |     0.9388 |   0.066368
  400 |   0.003805 |     0.9811 |     0.9522 |   0.069550
  450 |   0.002159 |     0.9815 |     0.9611 |   0.071042
  500 |   0.001462 |     0.9816 |     0.9669 |   0.071536
  550 |   0.001154 |     0.9816 |     0.9707 |   0.071433
  600 |   0.001010 |     0.9816 |     0.9733 |   0.070969
  650 |   0.000933 |     0.9817 |     0.9751 |   0.070286
  700 |   0.000886 |     0.9819 |     0.9764 |   0.069473
  750 |   0.000851 |     0.9821 |     0.9774 |   0.068581
  800 |   0.000822 |     0.9823 |     0.9781 |   0.067646
  850 |   0.00

# Hypothesis without b

In [15]:
x_data = [[1.,1.,1.,1.,1.],
          [1.,0.,3.,0.,5.],
          [0.,2.,0.,4.,0.]]
y_data = [1,2,3,4,5]

W = tf.Variable(tf.random.uniform((1,3), -1.0, 1.0))
learning_rate = 0.001
optimizer = tf.keras.optimizers.SGD(learning_rate)

for i in range(1000+1):
    with tf.GradientTape() as tape:
        hypothesis = tf.matmul(W, x_data)
        cost = tf.reduce_mean(tf.square(hypothesis-y_data))
        
    grads = tape.gradient(cost,[W])
    optimizer.apply_gradients(grads_and_vars=zip(grads,[W]))
    
    if i % 50 == 0:
        print("{:5} | {:10.6f} | {:10.4f} | {:10.4f} | {:10.4f}".format(
            i, cost.numpy(), W.numpy()[0][0], W.numpy()[0][1], W.numpy()[0][2]))

    0 |   4.295470 |     0.1115 |     0.4252 |     0.2424
   50 |   1.279871 |     0.2461 |     0.6909 |     0.4742
  100 |   0.436048 |     0.3153 |     0.8098 |     0.6197
  150 |   0.173934 |     0.3506 |     0.8622 |     0.7122
  200 |   0.083689 |     0.3679 |     0.8849 |     0.7716
  250 |   0.049756 |     0.3754 |     0.8947 |     0.8102
  300 |   0.036006 |     0.3774 |     0.8989 |     0.8356
  350 |   0.029982 |     0.3764 |     0.9010 |     0.8525
  400 |   0.027051 |     0.3735 |     0.9023 |     0.8641
  450 |   0.025395 |     0.3697 |     0.9034 |     0.8722
  500 |   0.024279 |     0.3652 |     0.9045 |     0.8780
  550 |   0.023402 |     0.3604 |     0.9056 |     0.8824
  600 |   0.022637 |     0.3554 |     0.9069 |     0.8858
  650 |   0.021931 |     0.3503 |     0.9081 |     0.8886
  700 |   0.021261 |     0.3451 |     0.9094 |     0.8909
  750 |   0.020617 |     0.3400 |     0.9107 |     0.8930
  800 |   0.019996 |     0.3350 |     0.9120 |     0.8949
  850 |   0.01

# Custom Gradient

In [21]:
X = tf.constant([[1.,2.],
                 [3.,4.]])
Y = tf.constant([[1.5], [3.5]])

W = tf.Variable(tf.random.normal((2,1)))
b = tf.Variable(tf.random.normal((1,)))

optimizer = tf.keras.optimizers.SGD(learning_rate=0.01)
n_epochs = 1000+1
print("Epoch | cost")
for i in range(n_epochs):
    with tf.GradientTape() as tape:
        y_pred = tf.matmul(X,W) + b
        cost = tf.reduce_mean(tf.square(y_pred-Y))
        
    grads = tape.gradient(cost,[W,b])
    
    optimizer.apply_gradients(grads_and_vars=zip(grads,[W,b]))
    
    if i % 50 == 0:
        print("{:5} | {:10.6f}".format(i, cost.numpy()))

Epoch | cost
    0 |  46.622746
   50 |   0.727939
  100 |   0.497699
  150 |   0.340281
  200 |   0.232653
  250 |   0.159067
  300 |   0.108756
  350 |   0.074357
  400 |   0.050839
  450 |   0.034759
  500 |   0.023765
  550 |   0.016248
  600 |   0.011109
  650 |   0.007595
  700 |   0.005193
  750 |   0.003551
  800 |   0.002428
  850 |   0.001660
  900 |   0.001135
  950 |   0.000776
 1000 |   0.000530



# Predicting exam score

In [23]:
x1 = [73., 93., 89., 96., 73.]
x2 = [80., 88., 91., 98., 66.]
x3 = [75., 83., 90., 100., 70.]
Y = [152., 185., 180., 196., 142.]

w1 = tf.Variable(10.)
w2 = tf.Variable(10.)
w3 = tf.Variable(10.)
b = tf.Variable(10.)

learning_rate = 0.000001

for i in range(1000+1):
    with tf.GradientTape() as tape:
        hypothesis = w1*x1 + w2*x2 + w3*x3 + b
        cost = tf.reduce_mean(tf.square(hypothesis-Y))
        
    w1_grad,w2_grad,w3_grad,b_grad = tape.gradient(cost,[w1,w2,w3,b])
    
    w1.assign_sub(learning_rate*w1_grad)
    w2.assign_sub(learning_rate*w2_grad)
    w3.assign_sub(learning_rate*w3_grad)
    b.assign_sub(learning_rate*b_grad)
    
    
    if i % 50 == 0:
        print("{:5} | {:12.4f}".format(i, cost.numpy()))

    0 | 5693289.5000
   50 |   68107.7344
  100 |     828.8473
  150 |      24.1404
  200 |      14.4862
  250 |      14.3413
  300 |      14.3101
  350 |      14.2803
  400 |      14.2507
  450 |      14.2212
  500 |      14.1917
  550 |      14.1623
  600 |      14.1331
  650 |      14.1039
  700 |      14.0747
  750 |      14.0457
  800 |      14.0167
  850 |      13.9878
  900 |      13.9589
  950 |      13.9302
 1000 |      13.9015


## Matrix 사용

In [29]:
data = np.array([[73., 80.,75., 152.],
                 [93., 88., 93., 185.],
                 [89., 91., 90., 180.],
                 [96., 98., 100., 196.],
                 [73., 66., 70., 142.]],dtype=np.float32)

X = data[:,:-1]
Y = data[:,[-1]]

W = tf.Variable(tf.random.normal((3,1)))
b = tf.Variable(tf.random.normal((1,)))

learning_rate = 0.000001

def predict(X):
    return tf.matmul(X,W) + b
print("Epoch | cost")

n_epochs = 2000

for i in range(n_epochs + 1):
    with tf.GradientTape() as tape:
        cost = tf.reduce_mean(tf.square(predict(X) - Y))
        
    W_grad, b_grad = tape.gradient(cost,[W,b])
    
    W.assign_sub(learning_rate * W_grad)
    b.assign_sub(learning_rate * b_grad)
    
    if i % 100 == 0:
        print("{:5} | {:10.4f}".format(i, cost.numpy()))

Epoch | cost
    0 |  6573.8047
  100 |    42.8227
  200 |    41.7962
  300 |    41.5749
  400 |    41.3549
  500 |    41.1361
  600 |    40.9186
  700 |    40.7021
  800 |    40.4868
  900 |    40.2728
 1000 |    40.0598
 1100 |    39.8480
 1200 |    39.6373
 1300 |    39.4278
 1400 |    39.2194
 1500 |    39.0122
 1600 |    38.8061
 1700 |    38.6010
 1800 |    38.3972
 1900 |    38.1943
 2000 |    37.9927


In [30]:
W.numpy()

array([[-0.36475807],
       [ 1.601843  ],
       [ 0.7778937 ]], dtype=float32)

In [31]:
b.numpy()

array([-0.38048247], dtype=float32)

In [32]:
tf.matmul(X,W) + b

<tf.Tensor: id=344360, shape=(5, 1), dtype=float32, numpy=
array([[159.48166],
       [179.00333],
       [182.9342 ],
       [199.37274],
       [133.16638]], dtype=float32)>

In [33]:
Y

array([[152.],
       [185.],
       [180.],
       [196.],
       [142.]], dtype=float32)

In [34]:
predict(X).numpy()

array([[159.48166],
       [179.00333],
       [182.9342 ],
       [199.37274],
       [133.16638]], dtype=float32)