# 내가 만든 Image 불러오기

In [1]:
import torch
import torch.nn as nn
import torch.nn.functional as F

import torch.optim as optim


import torchvision
import torchvision.transforms as transforms
from torch.utils.data import DataLoader

In [2]:
from matplotlib.pyplot import imshow
%matplotlib inline

In [3]:
%ls origin_data

 C 드라이브의 볼륨에는 이름이 없습니다.
 볼륨 일련 번호: 96ED-75D7

 C:\Users\wlska\Documents\DL_forALL\Pytorch\Part 03 CNN\origin_data 디렉터리

2020-02-14  오후 09:50    <DIR>          .
2020-02-14  오후 09:50    <DIR>          ..
2020-02-14  오후 09:50    <DIR>          gray
2020-02-14  오후 09:50    <DIR>          red
               0개 파일                   0 바이트
               4개 디렉터리  350,011,346,944 바이트 남음


In [4]:
#size 줄이기
trans = transforms.Compose([
    transforms.Resize((64,128))
])

train_data = torchvision.datasets.ImageFolder(root="origin_data/",
                                              transform=trans)

In [5]:
for num, value in enumerate(train_data):
    data, label = value
    print(num,data,label)
    
    if(label == 0):
        data.save("train_data/grey/%d_%d.jpeg" % (num,label))
    else:
        data.save("train_data/red/%d_%d.jpeg" % (num,label))
    
            

0 <PIL.Image.Image image mode=RGB size=128x64 at 0x1C77244A848> 0
1 <PIL.Image.Image image mode=RGB size=128x64 at 0x1C772454B88> 0
2 <PIL.Image.Image image mode=RGB size=128x64 at 0x1C772454C48> 0
3 <PIL.Image.Image image mode=RGB size=128x64 at 0x1C772454D88> 0
4 <PIL.Image.Image image mode=RGB size=128x64 at 0x1C772454E48> 0
5 <PIL.Image.Image image mode=RGB size=128x64 at 0x1C772454F08> 0
6 <PIL.Image.Image image mode=RGB size=128x64 at 0x1C772454FC8> 0
7 <PIL.Image.Image image mode=RGB size=128x64 at 0x1C77245D0C8> 0
8 <PIL.Image.Image image mode=RGB size=128x64 at 0x1C77245D188> 0
9 <PIL.Image.Image image mode=RGB size=128x64 at 0x1C77245D348> 0
10 <PIL.Image.Image image mode=RGB size=128x64 at 0x1C77245D408> 0
11 <PIL.Image.Image image mode=RGB size=128x64 at 0x1C77245D4C8> 0
12 <PIL.Image.Image image mode=RGB size=128x64 at 0x1C77245D588> 0
13 <PIL.Image.Image image mode=RGB size=128x64 at 0x1C77245D648> 0
14 <PIL.Image.Image image mode=RGB size=128x64 at 0x1C77245D708> 0
15 <P

138 <PIL.Image.Image image mode=RGB size=128x64 at 0x1C772466408> 0
139 <PIL.Image.Image image mode=RGB size=128x64 at 0x1C772454B48> 0
140 <PIL.Image.Image image mode=RGB size=128x64 at 0x1C77245D348> 0
141 <PIL.Image.Image image mode=RGB size=128x64 at 0x1C77245D708> 0
142 <PIL.Image.Image image mode=RGB size=128x64 at 0x1C77245D408> 0
143 <PIL.Image.Image image mode=RGB size=128x64 at 0x1C77245D748> 0
144 <PIL.Image.Image image mode=RGB size=128x64 at 0x1C77245D448> 0
145 <PIL.Image.Image image mode=RGB size=128x64 at 0x1C77245DDC8> 0
146 <PIL.Image.Image image mode=RGB size=128x64 at 0x1C77245DAC8> 0
147 <PIL.Image.Image image mode=RGB size=128x64 at 0x1C77245DD08> 0
148 <PIL.Image.Image image mode=RGB size=128x64 at 0x1C772460348> 0
149 <PIL.Image.Image image mode=RGB size=128x64 at 0x1C7724604C8> 0
150 <PIL.Image.Image image mode=RGB size=128x64 at 0x1C7724601C8> 0
151 <PIL.Image.Image image mode=RGB size=128x64 at 0x1C772460508> 0
152 <PIL.Image.Image image mode=RGB size=128x64 

282 <PIL.Image.Image image mode=RGB size=128x64 at 0x1C7724688C8> 0
283 <PIL.Image.Image image mode=RGB size=128x64 at 0x1C77245D508> 0
284 <PIL.Image.Image image mode=RGB size=128x64 at 0x1C772454D88> 0
285 <PIL.Image.Image image mode=RGB size=128x64 at 0x1C772454B48> 0
286 <PIL.Image.Image image mode=RGB size=128x64 at 0x1C772460048> 0
287 <PIL.Image.Image image mode=RGB size=128x64 at 0x1C772460708> 0
288 <PIL.Image.Image image mode=RGB size=128x64 at 0x1C772460D08> 0
289 <PIL.Image.Image image mode=RGB size=128x64 at 0x1C772460408> 0
290 <PIL.Image.Image image mode=RGB size=128x64 at 0x1C7724630C8> 0
291 <PIL.Image.Image image mode=RGB size=128x64 at 0x1C772463408> 0
292 <PIL.Image.Image image mode=RGB size=128x64 at 0x1C772463F08> 0
293 <PIL.Image.Image image mode=RGB size=128x64 at 0x1C772463648> 0
294 <PIL.Image.Image image mode=RGB size=128x64 at 0x1C772465188> 0
295 <PIL.Image.Image image mode=RGB size=128x64 at 0x1C7724650C8> 0
296 <PIL.Image.Image image mode=RGB size=128x64 

423 <PIL.Image.Image image mode=RGB size=128x64 at 0x1C77246ABC8> 1
424 <PIL.Image.Image image mode=RGB size=128x64 at 0x1C77245DDC8> 1
425 <PIL.Image.Image image mode=RGB size=128x64 at 0x1C772460188> 1
426 <PIL.Image.Image image mode=RGB size=128x64 at 0x1C772463F08> 1
427 <PIL.Image.Image image mode=RGB size=128x64 at 0x1C772465B88> 1
428 <PIL.Image.Image image mode=RGB size=128x64 at 0x1C772465EC8> 1
429 <PIL.Image.Image image mode=RGB size=128x64 at 0x1C7724657C8> 1
430 <PIL.Image.Image image mode=RGB size=128x64 at 0x1C772466448> 1
431 <PIL.Image.Image image mode=RGB size=128x64 at 0x1C772466188> 1
432 <PIL.Image.Image image mode=RGB size=128x64 at 0x1C772466CC8> 1
433 <PIL.Image.Image image mode=RGB size=128x64 at 0x1C772466F48> 1
434 <PIL.Image.Image image mode=RGB size=128x64 at 0x1C772467048> 1
435 <PIL.Image.Image image mode=RGB size=128x64 at 0x1C772467748> 1
436 <PIL.Image.Image image mode=RGB size=128x64 at 0x1C772467808> 1
437 <PIL.Image.Image image mode=RGB size=128x64 

# Neural Network 만들기

In [10]:
device = "cuda" if torch.cuda.is_available() else "cpu"

torch.manual_seed(777)
if device=="cuda":
    torch.cuda.manual_seed_all(777)

In [11]:
#size 줄이기
trans = transforms.Compose([
    transforms.ToTensor()
])

# MNIST에선 torchvision.datasets.MNIST였다
train_data = torchvision.datasets.ImageFolder(root="train_data", transform=trans)

In [12]:
data_loader = DataLoader(dataset=train_data,batch_size = 8, shuffle=True, num_workers=2)

In [13]:
class CNN(nn.Module):
    def __init__(self):
        super(CNN,self).__init__()
        self.layer1 = nn.Sequential(
            nn.Conv2d(3,6,5),
            nn.ReLU(),
            nn.MaxPool2d(2)
        )
        
        self.layer2 = nn.Sequential(
            nn.Conv2d(6,16,5),
            nn.ReLU(),
            nn.MaxPool2d(2)
        )
        
        self.layer3 = nn.Sequential(
            nn.Linear(16*13*29,120),
            nn.ReLU(),
            nn.Linear(120,2)
        )
        
    def forward(self,x):
        out = self.layer1(x)
      #  print(out.shape)
        out = self.layer2(out)
      #  print(out.shape)
        out = out.view(out.shape[0],-1)
      #  print(out.shape)
        out = self.layer3(out)
      #  print(out.shape)
        return out

In [14]:
# testing
net = CNN().to(device)
test_input = torch.Tensor(3,3,64,128).to(device)
test_out = net(test_input)

In [15]:
optimizer = optim.Adam(net.parameters(),lr=0.00001)
loss_func = nn.CrossEntropyLoss().to(device)

In [18]:
total_batch = len(data_loader)

epochs = 5
for epoch in range(epochs):
    avg_cost = 0.0
    for num, data in enumerate(data_loader):
        imgs,labels = data
        imgs = imgs.to(device)
        labels = labels.to(device)
        optimizer.zero_grad()
        out = net(imgs)
        loss = loss_func(out,labels)
        loss.backward()
        optimizer.step()
        
        avg_cost += loss/total_batch
    print("[Epoch:{}] cost = {}".format(epoch+1,avg_cost))
    
print("Learning finished")

[Epoch:1] cost = 0.5435075759887695
[Epoch:2] cost = 0.45712074637413025
[Epoch:3] cost = 0.36233851313591003
[Epoch:4] cost = 0.2762024700641632
[Epoch:5] cost = 0.20337462425231934
Learning finished


## model save
- 학습시킨 model을 항상 쓸때마다 다시 학습시켜서 사용할 순 없다
- torch.save()를 이용해서 그 network의 state_dict를 저장하자

In [20]:
torch.save(net.state_dict(), "./model/model.pth")

In [21]:
new_net = CNN().to(device)

In [23]:
new_net.load_state_dict(torch.load("./model/model.pth")) # 저장한 model 불러오기

<All keys matched successfully>

In [24]:
print(net.layer1[0])
print(new_net.layer1[0])

print(net.layer1[0].weight[0][0][0])
print(new_net.layer1[0].weight[0][0][0])

net.layer1[0].weight[0] == new_net.layer1[0].weight[0]

Conv2d(3, 6, kernel_size=(5, 5), stride=(1, 1))
Conv2d(3, 6, kernel_size=(5, 5), stride=(1, 1))
tensor([-0.0955, -0.0009, -0.0212, -0.0252,  0.0892], device='cuda:0',
       grad_fn=<SelectBackward>)
tensor([-0.0955, -0.0009, -0.0212, -0.0252,  0.0892], device='cuda:0',
       grad_fn=<SelectBackward>)


tensor([[[True, True, True, True, True],
         [True, True, True, True, True],
         [True, True, True, True, True],
         [True, True, True, True, True],
         [True, True, True, True, True]],

        [[True, True, True, True, True],
         [True, True, True, True, True],
         [True, True, True, True, True],
         [True, True, True, True, True],
         [True, True, True, True, True]],

        [[True, True, True, True, True],
         [True, True, True, True, True],
         [True, True, True, True, True],
         [True, True, True, True, True],
         [True, True, True, True, True]]], device='cuda:0')

In [25]:
trans = torchvision.transforms.Compose([
    transforms.Resize((64,128)),
    transforms.ToTensor()
])


test_data = torchvision.datasets.ImageFolder(root="./test_data",transform=trans)

In [26]:
test_set = DataLoader(dataset=test_data, batch_size=len(test_data))

In [27]:
with torch.no_grad():
    for num, data in enumerate(test_set):
        imgs,label = data
        imgs = imgs.to(device)
        label = label.to(device)
        
        prediction = net(imgs)
        
        correct_prediction = torch.argmax(prediction,1) == label
        
        accuracy = correct_prediction.float().mean()
        print("Accuracy:", accuracy.item())

Accuracy: 1.0
